add landing message #1
AttwoodData/Project5 pull request #2
Opened 2022-10-25 22:33 UTC by OsamaAater

2022-10-25 22:33 UTC, AttwoodData commented
I am not convinced about your <h1> code. Please convince me.

2022-10-25 22:56 UTC, OsamaAater reviewed
I improved the code.

2022-10-28 14:50 UTC, AttwoodData approved these changes
The changes look good!

2022-10-28 14:52 UTC, AttwoodData commented on index.html
> +<h1>
This looks good!

2022-10-28 14:54 UTC, AttwoodData requested changes
Make a change here

2022-10-28 14:57 UTC, OsamaAater commented
Changes implemented.

2022-10-28 14:58 UTC, AttwoodData approved these changes
This looks good!

2022-10-28 15:01 UTC, AttwoodData approved these changes

2022-10-28 15:02 UTC, merged

2022-10-28 15:08 UTC, AttwoodData commented
Can I close the issue?